In [1]:
# Artificial Neural Networks
# The Neuron
# The Activation Function
# Working of NN
# Learning of NN
# Gradient Discent
# Stochastic Gradient Discent
# Back Propagation

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [4]:
sb.set()

In [3]:
df=pd.read_csv("Churn_Modelling.csv")

In [5]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [12]:
lbl1=LabelEncoder()
x[:,1]=lbl1.fit_transform(x[:,1])


In [16]:
lbl2=LabelEncoder()
x[:,2]=lbl2.fit_transform(x[:,2])

In [19]:
ohe=OneHotEncoder(categorical_features=[1])
x=ohe.fit_transform(x).toarray()

e:\pypro\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [21]:
x=x[:,1:]

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [27]:
import keras
from keras.models import Sequential
from keras.layers import Dense


In [29]:
clas=Sequential()

W0403 07:53:21.845677  7060 deprecation_wrapper.py:119] From e:\pypro\venv\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [31]:
clas.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))
clas.add(Dropout(p=0.1)) # to improve ANN and to reduce overfitting

e:\pypro\venv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [32]:
clas.add(Dense(output_dim=6, init='uniform', activation='relu'))
clas.add(Dropout(p=0.1))

e:\pypro\venv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [33]:
clas.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))

e:\pypro\venv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [34]:
clas.compile(optimizer='adam', loss='binary_crossentropy', mertrics=['accuracy'])

W0403 07:59:53.857087  7060 deprecation_wrapper.py:119] From e:\pypro\venv\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



In [36]:
clas.fit(x_train,y_train, batch_size=10, nb_epoch=100)

Epoch 1/100
 420/8000 [>.............................] - ETA: 2s - loss: 0.4062

e:\pypro\venv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 3s 351us/step - loss: 0.4063
Epoch 2/100
8000/8000 [==============================] - 3s 352us/step - loss: 0.4059
Epoch 3/100
8000/8000 [==============================] - 3s 353us/step - loss: 0.4053
Epoch 4/100
8000/8000 [==============================] - 3s 374us/step - loss: 0.4057
Epoch 5/100
8000/8000 [==============================] - 3s 346us/step - loss: 0.4050
Epoch 6/100
8000/8000 [==============================] - 3s 343us/step - loss: 0.4054
Epoch 7/100
8000/8000 [==============================] - 3s 349us/step - loss: 0.4050
Epoch 8/100
8000/8000 [==============================] - 3s 348us/step - loss: 0.4044
Epoch 9/100
8000/8000 [==============================] - 3s 347us/step - loss: 0.4047
Epoch 10/100
8000/8000 [==============================] - 3s 349us/step - loss: 0.4046
Epoch 11/100
8000/8000 [==============================] - 3s 346us/step - loss: 0.4052
Epoch 12/100
8000/8000 [==============================] - 3s 345

8000/8000 [==============================] - 3s 335us/step - loss: 0.4027
Epoch 96/100
8000/8000 [==============================] - 3s 332us/step - loss: 0.4024
Epoch 97/100
8000/8000 [==============================] - 3s 334us/step - loss: 0.4024
Epoch 98/100
8000/8000 [==============================] - 3s 332us/step - loss: 0.4034
Epoch 99/100
8000/8000 [==============================] - 3s 339us/step - loss: 0.4032
Epoch 100/100
8000/8000 [==============================] - 3s 335us/step - loss: 0.4028


In [38]:
ypred=clas.predict(x_test)
ypred=(ypred>0.5)

In [39]:
ypred[7]

array([False])

In [40]:
from sklearn.metrics import confusion_matrix

In [41]:
print(confusion_matrix(y_test,ypred))

[[1543   64]
 [ 251  142]]


In [42]:
from sklearn.metrics import classification_report

In [43]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91      1607
           1       0.69      0.36      0.47       393

    accuracy                           0.84      2000
   macro avg       0.77      0.66      0.69      2000
weighted avg       0.83      0.84      0.82      2000



In [45]:
# Prediction of a new Customer
new=clas.predict(sc.transform(np.array([[0.0, 0, 600 , 1, 40, 3, 60000, 2, 1, 1, 35000]])))
new=(new>0.5)

In [46]:
new

array([[False]])

In [ ]:
# K-Fold Cross Validation

In [53]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense
def build_classifier():
    clas=Sequential()
    clas.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))
    clas.add(Dense(output_dim=6, init='uniform', activation='relu'))
    clas.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))
    clas.compile(optimizer='adam', loss='binary_crossentropy', mertrics=['accuracy'])
    return clas

clas = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)
acc = cross_val_score(estimator = clas, X = x_train, y = y_train, cv = 10, n_jobs = -1)

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

In [ ]:
mean = acc.mean()
var = acc.std()
# that's how we obtain the best 

In [ ]:
# Tuning the ANN

In [54]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    clas=Sequential()
    clas.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))
    clas.add(Dense(output_dim=6, init='uniform', activation='relu'))
    clas.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))
    clas.compile(optimizer=optimizer, loss='binary_crossentropy', mertrics=['accuracy'])
    return clas

clas = KerasClassifier(build_fn = build_classifier)

parameters = {'batch_size' : [20,30], 'nb_epoch' : [100,300], 'optimizer' : ['adam' , 'rmsprop']}

grid_search = GridSearchCV(estimator= clas, param_grid=parameters, scoring='accuracy', cv=10)
grid_search = grid_search.fit(x_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_


# this'll give you the best parameters as well as the best ANN model suited

e:\pypro\venv\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  import sys
e:\pypro\venv\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
e:\pypro\venv\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if __name__ == '__main__':
e:\pypro\venv\lib\site-packages\sklearn\model_selection\_validation.py:528: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


ValueError: ('Some keys in session_kwargs are not supported at this time: %s', dict_keys(['mertrics']))